//! The flake inputs table in `docs/THIRD-PARTY-NOTICES.md`, between
//! `<!-- BEGIN inputs ... -->` and `<!-- END inputs -->`, from what
//! `flake.lock` locks (dev:V1). The licence prose around it stays
//! hand-written.

use std::fmt::Write as _;

use crate::json::{self, Json};

/// The block's name.
pub const NAME: &str = "inputs";

/// Characters of a revision the table shows, as `git log --oneline` does.
const SHORT: usize = 7;

/// One locked flake input.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Input {
    /// The node's name in `flake.lock`.
    pub name: String,
    /// Where it is fetched from, as a flake reference: `git+https://…`
    /// or `github:owner/repo`.
    pub source: String,
    /// The branch or tag it follows, if the lock records one.
    pub reference: Option<String>,
    /// The locked revision, short; `None` for an input without one.
    pub rev: Option<String>,
    /// The lock's `type`: `git`, `github`, ...
    pub kind: String,
}

/// Every locked node of `flake.lock`, sorted by name, the root excluded.
///
/// # Errors
///
/// When the text is not a lock file or locks nothing (dev:V1), naming
/// `flake.lock`.
pub fn inputs(lock: &str) -> Result<Vec<Input>, String> {
    let lock = json::parse(lock).ok_or("flake.lock is not JSON")?;
    let root = lock.get("root").and_then(Json::as_str).unwrap_or("root");
    let nodes = lock
        .get("nodes")
        .map(Json::members)
        .ok_or("flake.lock has no `nodes`")?;
    let mut found: Vec<Input> = nodes
        .iter()
        .filter(|(name, _)| name != root)
        .filter_map(|(name, node)| input(name, node))
        .collect();
    if found.is_empty() {
        return Err("flake.lock locks no input; run nix flake lock".to_owned());
    }
    found.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(found)
}

/// One node, if it is locked.
fn input(name: &str, node: &Json) -> Option<Input> {
    let locked = node.get("locked")?;
    let text = |key: &str| locked.get(key).and_then(Json::as_str);
    let kind = text("type")?;
    let source = match (text("url"), text("owner"), text("repo"), text("path")) {
        (Some(url), ..) if url.starts_with(&format!("{kind}+")) => url.to_owned(),
        (Some(url), ..) if matches!(kind, "tarball" | "file") => url.to_owned(),
        (Some(url), ..) => format!("{kind}+{url}"),
        (None, Some(owner), Some(repo), _) => format!("{kind}:{owner}/{repo}"),
        (None, _, _, Some(path)) => format!("{kind}:{path}"),
        _ => kind.to_owned(),
    };
    let original = |key: &str| node.get("original")?.get(key).and_then(Json::as_str);
    let reference = text("ref").or_else(|| original("ref"));
    Some(Input {
        name: name.to_owned(),
        source,
        reference: reference.map(str::to_owned),
        rev: text("rev").map(|rev| rev.chars().take(SHORT).collect()),
        kind: kind.to_owned(),
    })
}

/// `text` as code, or `-` when there is none.
fn code(text: Option<&str>) -> String {
    text.map_or_else(|| "-".to_owned(), |text| format!("`{text}`"))
}

/// The table block, markers included, ending in a newline.
#[must_use]
pub fn table(inputs: &[Input]) -> String {
    let mut out = format!(
        "<!-- BEGIN {NAME}: generated by `claudinix-dev notices --write` from flake.lock; do not edit -->\n\
         | input | source | ref | locked rev | type |\n\
         |---|---|---|---|---|\n"
    );
    for input in inputs {
        let _ = writeln!(
            out,
            "| `{}` | `{}` | {} | {} | {} |",
            input.name,
            input.source,
            code(input.reference.as_deref()),
            code(input.rev.as_deref()),
            input.kind
        );
    }
    let _ = writeln!(out, "<!-- END {NAME} -->");
    out
}

#[cfg(test)]
mod tests;
