//! The inputs table, from a fixture lock in flake.lock's own shape.

use super::{Input, inputs, table};

const LOCK: &str = r#"{
  "nodes": {
    "cavekit": {
      "flake": false,
      "locked": {
        "lastModified": 1786745271,
        "narHash": "sha256-x",
        "ref": "main",
        "rev": "7421e87d5b517c415c519ddf58a3dd10ba842530",
        "shallow": true,
        "type": "git",
        "url": "https://github.com/JuliusBrussee/cavekit"
      },
      "original": {
        "ref": "main",
        "type": "git",
        "url": "https://github.com/JuliusBrussee/cavekit"
      }
    },
    "nixpkgs": {
      "locked": {
        "lastModified": 1790920529,
        "narHash": "sha256-y",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "774debe7a0d1b496e35677ad955a1011c6ff74f3",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixos-26.05",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "local": {
      "locked": {
        "path": "/some/dir",
        "type": "path"
      },
      "original": {
        "path": "/some/dir",
        "type": "path"
      }
    },
    "root": {
      "inputs": {
        "cavekit": "cavekit",
        "local": "local",
        "nixpkgs": ["cavekit", "nixpkgs"]
      }
    }
  },
  "root": "root",
  "version": 7
}
"#;

fn input(
    name: &str,
    source: &str,
    reference: Option<&str>,
    rev: Option<&str>,
    kind: &str,
) -> Input {
    Input {
        name: name.to_owned(),
        source: source.to_owned(),
        reference: reference.map(str::to_owned),
        rev: rev.map(str::to_owned),
        kind: kind.to_owned(),
    }
}

#[test]
fn every_locked_node_is_read_sorted_without_the_root() {
    assert_eq!(
        inputs(LOCK),
        Ok(vec![
            input(
                "cavekit",
                "git+https://github.com/JuliusBrussee/cavekit",
                Some("main"),
                Some("7421e87"),
                "git"
            ),
            input("local", "path:/some/dir", None, None, "path"),
            input(
                "nixpkgs",
                "github:NixOS/nixpkgs",
                Some("nixos-26.05"),
                Some("774debe"),
                "github"
            ),
        ])
    );
}

/// dev:V1: a lock that locks nothing, or is not one, is an error naming
/// flake.lock, never an empty table.
#[test]
fn a_lock_without_inputs_is_refused_naming_it() {
    let empty = r#"{"nodes": {"root": {}}, "root": "root", "version": 7}"#;
    for bad in [empty, "", "{", "[]", r#"{"nodes": 1}"#] {
        let refused = inputs(bad).err().unwrap_or_default();
        assert!(refused.contains("flake.lock"), "{bad:?}: {refused:?}");
    }
}

#[test]
fn the_table_has_one_row_per_input_between_the_markers() {
    let block = table(&inputs(LOCK).unwrap_or_default());
    assert_eq!(
        block,
        "<!-- BEGIN inputs: generated by `claudinix-dev notices --write` from flake.lock; do not edit -->
| input | source | ref | locked rev | type |
|---|---|---|---|---|
| `cavekit` | `git+https://github.com/JuliusBrussee/cavekit` | `main` | `7421e87` | git |
| `local` | `path:/some/dir` | - | - | path |
| `nixpkgs` | `github:NixOS/nixpkgs` | `nixos-26.05` | `774debe` | github |
<!-- END inputs -->
"
    );
}
